address = "127.0.0.1"
port = 2223

db_url = "mysql://username:password@host:port/db"

rounds_cache_delay_secs = 600

# Uncomment to use live data from DB
mock_runtimes_data = "mock_runtimes_data.json"
